### PR TITLE
Reformat Warnings Labels

### PR DESCRIPTION
**Pull request by caitlynachen**
Before: 
image (3)
After:
Screen Shot 2020-11-19 at 3 20 03 PM
Screen Shot 2020-11-19 at 3 33 43 PM

### CODE REVIEW

**Comment by caitlynachen** [comment]
https://github.com/lux-org/lux/issues/145

**Comment by dorisjlee** [comment]
Does the `warnings.formatwarning` need to be called in every file or can we make a global call for this inside the `__init__.py` just once so that it is applied across all warnings in the session?

**Comment by caitlynachen** [comment]
I did try to add the import warnings to the init, however since I don't think the imported warnings module can't be passed in throughout different files, the global import didn't work. Let me know if you'd like me to try anything else

**Comment by dorisjlee** [comment]
That makes sense. I was thinking about this in a session's perspective, but I guess there is no sharing of warning across the classes.

**Comment by dorisjlee** [comment]
Could you fix the failing Travis test case?

**Review by dorisjlee — APPROVED** [review]

**Review by jerrysong1324 — APPROVED** [review]

**Comment by dorisjlee** [comment]
Thanks @caitlynachen !

**Pull request merged**
